import img1 from '../../images/examplesOfWork/ex1.jpg'
import img2 from '../../images/examplesOfWork/ex2.jpg'
import img3 from '../../images/examplesOfWork/ex3.jpg'
import img4 from '../../images/examplesOfWork/ex4.jpg'
import img5 from '../../images/examplesOfWork/ex5.jpg'
import img6 from '../../images/examplesOfWork/ex6.jpg'
import img7 from '../../images/examplesOfWork/ex7.jpg'
import img8 from '../../images/examplesOfWork/ex8.jpg'
import img9 from '../../images/examplesOfWork/ex9.jpg'
import img10 from '../../images/examplesOfWork/ex10.jpg'
import img11 from '../../images/examplesOfWork/ex11.jpg'
import img12 from '../../images/examplesOfWork/ex12.jpg'
import img13 from '../../images/examplesOfWork/ex13.jpg'
import img14 from '../../images/examplesOfWork/ex14.jpg'
import img15 from '../../images/examplesOfWork/ex15.jpg'

export const images = [img1, img2, img3, img4, img5, img6, img7, img9, img11, img12, img13, img14, img15]